[package]
name = "ghost-talk-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
[lib]
name = "ghost_talk_native_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
ghost-core = { path = "../../ghost-core" }
ghost-protocol = { path = "../../ghost-protocol" }
ghost-accounts = { path = "../../ghost-accounts" }
ghost-kaspa = { path = "../../ghost-kaspa", features = ["upstream"] }
ghost-hydra = { path = "../../ghost-hydra", features = ["upstream"] }
ghost-rooms = { path = "../../ghost-rooms" }
ghost-storage = { path = "../../ghost-storage" }
ghost-history = { path = "../../ghost-history" }
ghost-names = { path = "../../ghost-names" }
reqwest.workspace = true
tokio.workspace = true
hex.workspace = true
qrcode.workspace = true
zeroize.workspace = true
aes-gcm.workspace = true
rand.workspace = true
sha2.workspace = true
base64.workspace = true

kassigner-sdk.workspace = true
kassigner-protocol.workspace = true
rqrr.workspace = true
