[package]
name = "ghost-names"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
default = []


[dependencies]
serde.workspace = true
thiserror.workspace = true
reqwest.workspace = true
serde_json.workspace = true
hex.workspace = true
blake3.workspace = true
secp256k1 = "0.29.1"
tokio.workspace = true
kaspa-portal.workspace = true
ghost-domain = { path = "../ghost-domain" }
