[package]
name = "ghost-talk-native"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
[lib]
name = "ghost_talk_native_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
ghost-api = { path = "../ghost-api" }
ghost-kaskold = { path = "../ghost-kaskold" }
ghost-domain = { path = "../ghost-domain" }
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
ghost-talk.workspace = true
ghost-core = { path = "../ghost-core" }
ghost-protocol = { path = "../ghost-protocol" }
ghost-realtime.workspace = true
ghost-kaspa = { path = "../ghost-kaspa", features = ["upstream"] }
kaspa-portal.workspace = true
ghost-hydra = { path = "../ghost-hydra", features = ["native"] }
ghost-storage = { path = "../ghost-storage" }
ghost-history = { path = "../ghost-history" }
ghost-names = { path = "../ghost-names" }
reqwest.workspace = true
tokio.workspace = true
hex.workspace = true
zeroize.workspace = true
aes-gcm.workspace = true
rand.workspace = true
sha2.workspace = true
base64.workspace = true
ghost-media = { path = "../ghost-media" }
ghost-broadcast = { path = "../ghost-broadcast" }
ghost-kasia = { path = "../ghost-kasia", features = ["native"] }
ghost-indexer = { path = "../ghost-indexer" }
